import { Tool, Category } from '../types';

export const categories: Category[] = [
  { id: '1', name: 'Writing', slug: 'writing' },
  { id: '2', name: 'Image Generation', slug: 'image-generation' },
  { id: '3', name: 'Coding', slug: 'coding' },
  { id: '4', name: 'Video Editing', slug: 'video-editing' },
  { id: '5', name: 'Audio', slug: 'audio' },
  { id: '6', name: 'Productivity', slug: 'productivity' },
  { id: '7', name: 'Research', slug: 'research' },
];

export const mockTools: Tool[] = [
  {
    id: '1',
    name: 'ChatGPT',
    description: 'ChatGPT is OpenAI\'s revolutionary conversational AI that can understand and generate human-like text. Perfect for content creation, coding assistance, research, and creative writing. With its advanced language model, it can help with everything from answering complex questions to writing emails, creating marketing copy, and even debugging code.',
    category: categories[0],
    website_url: 'https://chat.openai.com',
    pricing: 'Freemium',
    features: ['Natural language conversations', 'Code generation and debugging', 'Creative writing assistance', 'Research and analysis', 'Multiple language support', 'Context-aware responses'],
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/1024px-ChatGPT_logo.svg.png',
    rating: 4.8,
    review_count: 1250,
    created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'Midjourney',
    description: 'Midjourney is a cutting-edge AI art generator that transforms text descriptions into stunning visual artwork. Used by artists, designers, and creators worldwide, it excels at creating everything from photorealistic images to abstract art, concept designs, and marketing visuals. The tool understands artistic styles, lighting, composition, and can mimic famous artists\' techniques.',
    category: categories[1],
    website_url: 'https://midjourney.com',
    pricing: 'Paid',
    features: ['Text-to-image generation', 'Multiple artistic styles', 'High-resolution outputs', 'Style variations and remixing', 'Commercial usage rights', 'Community gallery'],
    logo_url: 'https://seeklogo.com/images/M/midjourney-logo-F65C54C677-seeklogo.com.png',
    rating: 4.7,
    review_count: 890,
    created_at: '2024-01-02',
  },
  {
    id: '3',
    name: 'GitHub Copilot',
    description: 'GitHub Copilot is an AI-powered coding assistant that acts as your pair programmer. Trained on billions of lines of code, it provides intelligent code suggestions, auto-completions, and can generate entire functions from comments. It supports dozens of programming languages and integrates seamlessly with popular IDEs, dramatically speeding up development workflows.',
    category: categories[2],
    website_url: 'https://github.com/features/copilot',
    pricing: 'Paid',
    features: ['Intelligent code completion', '50+ programming languages', 'IDE integration', 'Function generation from comments', 'Code explanation and documentation', 'Security vulnerability detection'],
    logo_url: 'https://avatars.githubusercontent.com/u/44036562?s=280&v=4',
    rating: 4.6,
    review_count: 2100,
    created_at: '2024-01-03',
  },
  {
    id: '4',
    name: 'DALL-E 3',
    description: 'DALL-E 3 represents the latest advancement in AI image generation from OpenAI. It creates incredibly detailed and accurate images from text descriptions, with improved understanding of nuance, style, and composition. Perfect for marketing materials, concept art, social media content, and creative projects that require unique, custom imagery.',
    category: categories[1],
    website_url: 'https://openai.com/dall-e-3',
    pricing: 'Paid',
    features: ['Advanced text-to-image generation', 'Improved prompt understanding', 'High-resolution outputs', 'Style consistency', 'Safety filters', 'Commercial licensing'],
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/OpenAI_Logo.svg/1024px-OpenAI_Logo.svg.png',
    rating: 4.5,
    review_count: 750,
    created_at: '2024-01-04',
  },
  {
    id: '5',
    name: 'Grammarly',
    description: 'Grammarly is the world\'s leading AI writing assistant that helps millions of users write clearly and effectively. Beyond basic grammar and spell-checking, it provides advanced suggestions for tone, clarity, engagement, and delivery. Whether you\'re writing emails, reports, or creative content, Grammarly ensures your writing is polished and professional.',
    category: categories[5],
    website_url: 'https://grammarly.com',
    pricing: 'Freemium',
    features: ['Advanced grammar checking', 'Tone and style suggestions', 'Plagiarism detection', 'Writing goals and metrics', 'Browser extension', 'Team collaboration features'],
    logo_url: 'https://1000logos.net/wp-content/uploads/2023/05/Grammarly-Logo.png',
    rating: 4.4,
    review_count: 3200,
    created_at: '2024-01-05',
  },
  {
    id: '6',
    name: 'Runway ML',
    description: 'Runway ML is a comprehensive AI video editing platform that brings Hollywood-level effects to everyone. Create stunning videos with AI-powered tools for background removal, object tracking, style transfer, and motion graphics. Perfect for content creators, filmmakers, and marketers who want to produce professional-quality videos without extensive technical knowledge.',
    category: categories[3],
    website_url: 'https://runwayml.com',
    pricing: 'Freemium',
    features: ['AI video editing', 'Background removal', 'Style transfer', 'Motion tracking', 'Text-to-video generation', 'Real-time collaboration'],
    logo_url: 'https://app.runwayml.com/favicon.ico',
    rating: 4.3,
    review_count: 650,
    created_at: '2024-01-06',
  },
  {
    id: '7',
    name: 'ElevenLabs',
    description: 'ElevenLabs offers the most advanced AI voice synthesis technology available. Create incredibly realistic voiceovers, clone voices, and generate speech in multiple languages with emotional nuance. Ideal for podcasters, content creators, audiobook producers, and businesses needing high-quality voice content at scale.',
    category: categories[4],
    website_url: 'https://elevenlabs.io',
    pricing: 'Freemium',
    features: ['Realistic voice synthesis', 'Voice cloning', 'Multiple languages', 'Emotional control', 'API integration', 'Custom voice training'],
    logo_url: 'https://elevenlabs.io/favicon-32x32.png',
    rating: 4.6,
    review_count: 420,
    created_at: '2024-01-07',
  },
  {
    id: '8',
    name: 'Notion AI',
    description: 'Notion AI transforms your workspace into an intelligent productivity hub. Integrated directly into Notion\'s powerful note-taking and project management platform, it helps you write better, think clearer, and work faster. From generating meeting notes to creating project plans, Notion AI understands context and provides relevant, actionable assistance.',
    category: categories[5],
    website_url: 'https://notion.so/ai',
    pricing: 'Paid',
    features: ['Integrated workspace AI', 'Content generation', 'Meeting summaries', 'Project planning', 'Database automation', 'Template creation'],
    logo_url: 'https://www.notion.so/images/logo-ios.png',
    rating: 4.2,
    review_count: 890,
    created_at: '2024-01-08',
  },
  {
    id: '9',
    name: 'Perplexity',
    description: 'Perplexity is an AI-powered search engine that provides accurate, real-time answers with cited sources. It combines the power of large language models with up-to-date web search to deliver comprehensive responses to complex questions. Perfect for research, fact-checking, and getting reliable information on current events and specialized topics.',
    category: categories[6],
    website_url: 'https://perplexity.ai',
    pricing: 'Freemium',
    features: ['Real-time web search', 'Source citations', 'Follow-up questions', 'Multiple search modes', 'Academic research', 'Current events tracking'],
    logo_url: 'https://www.perplexity.ai/favicon.svg',
    rating: 4.5,
    review_count: 680,
    created_at: '2024-01-09',
  },
];